@echo off
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
python auau_Raider.py
